### PR TITLE
Cookiecut

### PR DESCRIPTION
**Pull request by MaceKuailv**
Changes related to CI

### CODE REVIEW

**Comment by malmans2** [comment]
Hi @MaceKuailv,
Let's start with the test data: It's taking too long to download data.
I see you copied the workflow form OceanSpy, but OceanSpy's is not ideal and extra-streps are needed because of some legacy code:

1. Do not store all files in a single tar archive, but store all of them separately. That way, pooch can cache all of them separately.
2. Do not download all of data first and don't use symlinks. Whenever test functions need to use files, just directly use pooch there.
3. You could use `fsspec` rather than `pooch`. The advantage is that it's very simple to use, and it's a dependency of dask, so very likely it's already installed.
Here is and example:
```python
import xarray as xr
import fsspec

def test_dummy():
    url = "https://github.com/pydata/xarray-data/raw/master/air_temperature.nc"
    with fsspec.open(f"simplecache::{url}") as f:
        ds = xr.open_dataset(f)
```

**Comment by malmans2** [comment]
And most importantly, make sure you reduce as much as possible the size of download data.
Even better, create the data from scratch whenever possible.
Sometimes you can just create yourself a dummy dataset, something like:
```python
import xarray as xr
import numpy as np

ds = xr.Dataset(
    {"foo": xr.DataArray(np.random.randn(2, 3, 4), dims=("time", "lat", "lon"))}
)
```

**Comment by MaceKuailv** [comment]
I think the first one is pretty straightforward to implement. But I am not sure how much do I need to reduce the size of the data. I am reluctant to generate the velocity field purely from scratch so I will preserve at least one snapshot of it. And of course, I need to store many of the coords. My estimate is that I could probably reduce it to around 20-50 mb. Is that enough?

Every time I upload to zenodo, it asks me something like "are you sure you want to do this? we will create a doi that will be forever". Is it OK to upload things frequently?

If I were to generate the data, where should I store the function that open and generate the data?

Do you have any other comments not related to the tests? I developed the test from main branch, so every change I made on the test from cookiecut branch will almost certainly cause a merge conflict. I would prefer we merge it first, and create a new branch for the test data problem.

**Comment by malmans2** [comment]
How about you merge this, and I will open issues with a few tips?

I also want to show you a couple of improvements/changes to the template, but I think it's easier if I open a PR.

I'll reply to the test question in a dedicated issue!

**Comment by MaceKuailv** [comment]
Very nice

**Pull request merged**
