### PR TITLE
various updates + GitHub workflow

### PR DESCRIPTION
**Pull request by malmans2**

### CODE REVIEW

**Comment by malmans2** [comment]
Hi @MaceKuailv,

I've cleaned up a few things and added the yaml to get started with CI worflows.
When you merge this, GH CI should start to work.

Main things I've changed:
1. I reviewed a bit the way you use pooch and fixtures.
2. I've added a few pre-commit hooks that you need for this project (e.g., notebooks linting)
3. I removed all docs _build. You should not include those in the GH repo

Tests an mypy are in good shape (i.e., `make unit-tests` and `make type-check` are OK).
There's a few issues to fix with QA and docs.

- `make qa` fails just because of a couple of minor fixes you have to apply to the notebooks.
- `make docs-build` also fails (not sure why, might be an easy fix)

Take a look at the changes and let me know if anything is not clear.
If it looks good, I suggest to merge and see if the CI works as expected (it should run, and fail because of QA and docs).

I have a few more comments, I'll open dedicated issues after you merge this, so it's easier to point to the code as well.

Great work! `seaduck` is already in very good shape!

**Comment by MaceKuailv** [comment]
Thank you so much! It would take me weeks to figure all of those things out, if I am able to do them correctly at all. I have a couple of questions:

1. Where is pandas-stubs and tqdm used? I did plan to use tqdm for my lagrangian particle as well, but that is of somewhat low priority. 
2. I realized that you put the reading test data function into tests/utils, which is smart. If I want to call the same function from notebooks, what should I do? Is it ok to just make this function part of seaduck/util. 
3. I saw you change the module names. I also realized that it can be annoying to have module names the same as class names. Is there a general naming convention when it comes to this?
4. I think in oceanspy you made all external packages look like _np? Is that necessary? I saw you change my _plt back into plt. 
5. There is several things I want to learn how to do, but it is already working. Like type-check, dependabot, etc.

I will merge it now. I think most of the problem with CI now is with the notebooks. I can adopt two of those notebooks with the test data I have now. I suppose the failure in building docs is also because the notebooks can not be executed.

**Comment by malmans2** [comment]
> Thank you so much! It would take me weeks to figure all of those things out, if I am able to do them correctly at all. I have a couple of questions:
> 
> 1. Where is pandas-stubs and tqdm used? I did plan to use tqdm for my lagrangian particle as well, but that is of somewhat low priority.

`pandas-stubs` are not really used at the moment because you're not really using type-checking. But if you'll start adding type annotations in the future, `pandas` will be properly checked. I added it so `mypy` doesn't complain.
`tqdm` is used by `pooch` I think, I've added `progressbar=True`.
BTW, they're both just useful for CI, which is why they're in `environment.ci`

> 2. I realized that you put the reading test data function into tests/utils, which is smart. If I want to call the same function from notebooks, what should I do? Is it ok to just make this function part of seaduck/util.

Yes! Actually, I think that would be even better!

> 3. I saw you change the module names. I also realized that it can be annoying to have module names the same as class names. Is there a general naming convention when it comes to this?

The convention is:
- `snake_case` for variables, functions, modules
- `CamelCase` for classes
- `ALL_CAPS` for global variables

> 4. I think in oceanspy you made all external packages look like _np? Is that necessary? I saw you change my _plt back into plt.

That's one of the worst choices I made in OceanSpy just because at the time I didn't know much about good practices. Don't import packages using private names.

> 5. There is several things I want to learn how to do, but it is already working. Like type-check, dependabot, etc.

You'll learn playing with it. Feel free to ask there's something you don't understand. BTW, beacuse I didn't test it it's very likely that we need to debug the CI files. We'll see...

> I will merge it now. I think most of the problem with CI now is with the notebooks. I can adopt two of those notebooks with the test data I have now. I suppose the failure in building docs is also because the notebooks can not be executed.

Not sure, I didn't really check it. I thought you said that you had somewhere a switch that turns off the execution of notebooks.

**Comment by malmans2** [comment]
Ahhh, workflow are not starting because the directory has the wrong name.
Rename `.github/workflow` to `.github/workflows`

**Comment by MaceKuailv** [comment]
You changed the _config file and turned on the execution option. It won't be a problem when I finished dealing with the notebook. 

I did convert all np to _np in utils. I will revert that and add the reading data functionality. Maybe some tools in creating the initial condition as well. 

Yes, I will rename that. It is well known that the Chinese is not good with plurals.:)

**Pull request merged**
