### PR TITLE
Aesthetic

### PR DESCRIPTION
**Pull request by MaceKuailv**
Mainly about the notebooks. Also change the code to make the notebook prettier.

### CODE REVIEW

**Comment by MaceKuailv** [comment]
I was wrong about the style check. 

@malmans2 what do you think overall?

**Comment by malmans2** [comment]
Hi @MaceKuailv, looks good!
All notebook in this repo will be executed when the documentation is compiled, right?
If yes, I would add the `pre-commit` hook that strips all notebook output:
```
- repo: https://github.com/kynan/nbstripout
  rev: 0.6.1
  hooks:
  - id: nbstripout
```

**Comment by malmans2** [comment]
Also, I suggest to print the `seaduck` version in the SciServer notebook:
```python
import seaduck as sd

print(sd.__version__)
```

**Comment by MaceKuailv** [comment]
Well, I may as well work on issue #26 from this PR as well, even though it is a bit low priority.

**Comment by MaceKuailv** [comment]
Address issue #13 #26 #27. The documentation certainly can use some improvement, but that's enough for this PR.

**Pull request merged**
