### PR TITLE
fix ci

### PR DESCRIPTION
**Pull request by malmans2**

### CODE REVIEW

**Comment by malmans2** [comment]
CI working (and failing as expected)... good to go!

**Comment by MaceKuailv** [comment]
The doc build was successful. That surprises me. 

I will cut and paste the changes to my new branch and close this pr when the new one is ready. Glad CI is working.

**Comment by malmans2** [comment]
You're right, it works. I misinterpreted the log, you just have a lot of warnings (try to fix those as well, otherwise eventually they'll become problems).
Something didn't work right with the distribution workflow. Let me try one thing.

**Comment by malmans2** [comment]
All good, you just have to fix the pre-commit problems with the notebooks

**Comment by MaceKuailv** [comment]
I'll just merge this despite the style checks failed for the notebook and fix the pre-commit in new PR.

**Pull request merged**
