### PR TITLE
Doc fixes for joss review

### PR DESCRIPTION
**Pull request by MaceKuailv**
I am going to group the first patch of fixes (mainly on documentations) in this PR.

### CODE REVIEW

**Comment by MaceKuailv** [comment]
This test failed because I added
```
raise Exception("I am a very bad boy!!") 
```
in one of the notebooks. and jupyter book is able to capture that. 

This is to test #92 and it seems to be working.

**Comment by MaceKuailv** [comment]
After turning on `-W --keep-going` in Jupyter Book, every warning in the documentation, including from both notebook tutorials and the help docstrings, is now captured in the CI system. 

The fact that the docs-build CI test passes means that both #91 and #92 are addressed.

**Comment by MaceKuailv** [comment]
Just added a new file on how to use the github issue channel properly. This should address issue #93

**Comment by MaceKuailv** [comment]
@pnsaevik Thank you very much for your suggestions. Please let me know if this PR addresses some of the problems and if I understand you correctly. I will merge this branch if you think at least some of the issue is resolved. 

Please feel welcomed to raise other issues or continue the discussion in existing ones. I really appreciate your comments.

**Review by pnsaevik — APPROVED** [review]

**Comment by pnsaevik** [comment]
I confirm that the pull request resolves issue #90, #91, #92 and #93. Good to hear that the comments are helpful :-) The package is very interesting, especially the Tracmass-style particle transport. I might try and write a plugin for ROMS ocean data some day.

**Comment by MaceKuailv** [comment]
That's very encouraging! 

I actually plan to do that as well. The only problem is that I don't have a ROMS dataset at hand. I think it should be easy (fingers crossed) because I always have that in mind and kept the grid handling pretty modular.

**Pull request merged**
